apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: quote-app
  labels:
    app: postgres
type: Opaque
data:
  # Base64 encoded values
  # echo -n 'quotes_password' | base64
  POSTGRES_PASSWORD: cXVvdGVzX3Bhc3N3b3Jk