global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'k6-performance-monitor'
    environment: 'development'

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # Sample application metrics
  - job_name: 'sample-app'
    static_configs:
      - targets: ['app:3000']
    scrape_interval: 15s
    metrics_path: /api/metrics
    scrape_timeout: 10s

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: /metrics

  # InfluxDB metrics
  - job_name: 'influxdb'
    static_configs:
      - targets: ['influxdb:8086']
    scrape_interval: 30s
    metrics_path: /metrics

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s
    metrics_path: /metrics

  # k6 Prometheus Remote Write (if configured)
  - job_name: 'k6-metrics'
    static_configs:
      - targets: ['k6:6565']  # k6 prometheus remote write endpoint
    scrape_interval: 5s
    metrics_path: /metrics
    scrape_timeout: 5s

# Remote write configuration for k6 metrics
remote_write:
  - url: "http://influxdb:8086/api/v1/prom/write?db=k6"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500