version: '3.8'

services:
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile.prod
    environment:
      NODE_ENV: production
    restart: always
    # Remove volume mounts for production

  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    restart: always
    # Remove volume mounts for production

  database:
    # Don't expose database port in production
    ports: []
    restart: always

  # Add reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    restart: always
    networks:
      - quote-network