global:
  # Global configuration for AlertManager
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@example.com'
  smtp_auth_username: 'alerts@example.com'
  smtp_auth_password: 'your-email-password'
  smtp_require_tls: true
  
  # Slack API URL (replace with your webhook URL)
  slack_api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
  
  # Default template files
  templates:
    - '/etc/alertmanager/templates/*.tmpl'

# Route tree for organizing alerts
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 5m
      
    # Warning alerts - less frequent notifications
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      repeat_interval: 30m
      
    # Database alerts
    - match:
        category: database
      receiver: 'database-team'
      
    # Infrastructure alerts
    - match:
        category: infrastructure
      receiver: 'infrastructure-team'
      
    # Application alerts
    - match:
        category: application
      receiver: 'application-team'
      
    # Business alerts
    - match:
        category: business
      receiver: 'business-team'
      
    # Security alerts
    - match:
        category: security
      receiver: 'security-team'
      group_wait: 0s
      repeat_interval: 15m

# Inhibition rules to suppress alerts
inhibit_rules:
  # Suppress warning alerts if critical alert is firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
    
  # Suppress individual service alerts if entire node is down
  - source_match:
      alertname: 'InstanceDown'
    target_match_re:
      alertname: '(ApplicationDown|DatabaseDown|HighCPUUsage|HighMemoryUsage)'
    equal: ['instance']

# Notification receivers
receivers:
  # Default receiver
  - name: 'default-receiver'
    email_configs:
      - to: 'admin@example.com'
        subject: '[ALERT] {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Labels: {{ range .Labels.SortedPairs }}{{ .Name }}={{ .Value }} {{ end }}
          {{ end }}
        headers:
          Priority: 'normal'
    
    slack_configs:
      - channel: '#alerts'
        title: 'Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          *Instance:* {{ .Labels.instance }}
          {{ end }}
        send_resolved: true
        
  # Critical alerts receiver
  - name: 'critical-alerts'
    email_configs:
      - to: 'oncall@example.com, admin@example.com'
        subject: '[CRITICAL] {{ .GroupLabels.alertname }}'
        body: |
          🚨 CRITICAL ALERT 🚨
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Runbook: {{ .Annotations.runbook_url }}
          Labels: {{ range .Labels.SortedPairs }}{{ .Name }}={{ .Value }} {{ end }}
          Started: {{ .StartsAt }}
          {{ end }}
        headers:
          Priority: 'high'
    
    slack_configs:
      - channel: '#critical-alerts'
        title: '🚨 CRITICAL: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Runbook:* {{ .Annotations.runbook_url }}
          *Instance:* {{ .Labels.instance }}
          *Started:* {{ .StartsAt }}
          {{ end }}
        send_resolved: true
        
    webhook_configs:
      - url: 'http://pagerduty-webhook:8080/webhook'
        send_resolved: true
        
  # Warning alerts receiver
  - name: 'warning-alerts'
    email_configs:
      - to: 'team@example.com'
        subject: '[WARNING] {{ .GroupLabels.alertname }}'
        body: |
          ⚠️ WARNING ALERT ⚠️
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Labels: {{ range .Labels.SortedPairs }}{{ .Name }}={{ .Value }} {{ end }}
          {{ end }}
    
    slack_configs:
      - channel: '#warnings'
        title: '⚠️ WARNING: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Instance:* {{ .Labels.instance }}
          {{ end }}
        send_resolved: true
        
  # Database team receiver
  - name: 'database-team'
    email_configs:
      - to: 'dba@example.com'
        subject: '[DB ALERT] {{ .GroupLabels.alertname }}'
        body: |
          🗄️ DATABASE ALERT 🗄️
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Database: {{ .Labels.datname }}
          Instance: {{ .Labels.instance }}
          {{ end }}
    
    slack_configs:
      - channel: '#database-alerts'
        title: '🗄️ DB: {{ .GroupLabels.alertname }}'
        send_resolved: true
        
  # Infrastructure team receiver
  - name: 'infrastructure-team'
    email_configs:
      - to: 'infra@example.com'
        subject: '[INFRA ALERT] {{ .GroupLabels.alertname }}'
        
    slack_configs:
      - channel: '#infrastructure-alerts'
        title: '🏗️ INFRA: {{ .GroupLabels.alertname }}'
        send_resolved: true
        
  # Application team receiver
  - name: 'application-team'
    email_configs:
      - to: 'dev@example.com'
        subject: '[APP ALERT] {{ .GroupLabels.alertname }}'
        
    slack_configs:
      - channel: '#application-alerts'
        title: '📱 APP: {{ .GroupLabels.alertname }}'
        send_resolved: true
        
  # Business team receiver
  - name: 'business-team'
    email_configs:
      - to: 'business@example.com'
        subject: '[BUSINESS ALERT] {{ .GroupLabels.alertname }}'
        
    slack_configs:
      - channel: '#business-alerts'
        title: '📊 BUSINESS: {{ .GroupLabels.alertname }}'
        send_resolved: true
        
  # Security team receiver
  - name: 'security-team'
    email_configs:
      - to: 'security@example.com'
        subject: '[SECURITY ALERT] {{ .GroupLabels.alertname }}'
        body: |
          🔒 SECURITY ALERT 🔒
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Source: {{ .Labels.instance }}
          Severity: {{ .Labels.severity }}
          Time: {{ .StartsAt }}
          {{ end }}
        headers:
          Priority: 'high'
    
    slack_configs:
      - channel: '#security-alerts'
        title: '🔒 SECURITY: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Source:* {{ .Labels.instance }}
          *Severity:* {{ .Labels.severity }}
          {{ end }}
        send_resolved: true
        
    webhook_configs:
      - url: 'http://security-webhook:8080/alert'
        send_resolved: true